client/COPYING.md
client/README.md

Just added copying so I can finally toss in icon without getting into legal trouble.

chore: added copying 

---

client/src/api/batch.ts
client/src/api/category.ts
client/src/api/document.ts
client/src/api/invite.ts
client/src/api/office.ts
client/src/api/snapshot.ts
client/src/api/staff.ts
client/src/api/user.ts

This PR literally just adds commas after the imports. I simply forgot to add them before. 😅

chore(fmt): add commas after imports

---

model/src/permission.ts

This PR (finally) establishes the bit string format that we will to validate local and global permissions throughout the system. To validate one or more permissions, we simply perform bitwise operations on a mask.
```ts
import { assertStrictEquals } from 'asserts';
// Set up the composite mask
const canAddAndUpdateStaff = Local.AddStaff | Local.UpdateStaff;
// Validate permissions
assertStrictEquals(permission & canAddAndUpdateStaff, canAddAndUpdateStaff);
```

feat(model): finalize permission bit string format

---

client/src/api/session.ts
server/src/routes/api/session.ts
server/src/routes/mod.ts

Allows both the client and the server to retrieve the user session.

feat: implement user getter from session

---

client/src/pages/Home.svelte
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/sw.ts
model/src/common.ts
server/src/database.ts
server/src/routes/auth/callback.ts
server/src/routes/auth/login.ts

This PR actually addresses multiple issues that prevent the dashboard from being rendered:
* Over-restrictive cookie scopes
* Incompatible data model of `UserSchema` between the server and the client

feat(client): implement boilerplate for dashboard

---

client/src/components/types.ts
client/src/components/ui/AcceptRow.svelte
client/src/components/ui/InboxRow.svelte
client/src/components/ui/InviteRow.svelte
client/src/components/ui/PersonRow.svelte
client/src/components/ui/RowTemplate.svelte
client/src/components/ui/row-element.css

This PR aims to add `RowTemplate.svelte` alongside other core components that depend on it, namely: `AcceptRow`, `InboxRow`, `PersonRow`, `InviteRow`.

feat(client): Added RowTemplate.svelte alongside other subcomponents.

---

client/src/components/types.ts
client/src/components/ui/AcceptContext.svelte
client/src/components/ui/AcceptRow.svelte
client/src/components/ui/InboxContext.svelte
client/src/components/ui/InboxRow.svelte
client/src/components/ui/InviteContext.svelte
client/src/components/ui/InviteRow.svelte
client/src/components/ui/PersonContext.svelte
client/src/components/ui/PersonRow.svelte
client/src/components/ui/contextmenu/ContextDivider.svelte
client/src/components/ui/contextmenu/ContextElement.svelte
client/src/components/ui/contextmenu/ContextTemplate.svelte
client/src/pages/global.css
client/src/pages/vars.css

This PR aims to implement context menus to the system.

feat(client): context menus

---

client/src/components/ui/Modal.svelte
client/src/pages/global.css

This PR aims to add the modal component.

feat(client): add modal components

---

client/src/components/ui/Select.svelte
client/src/pages/dashboard/views/Sandbox.svelte
client/src/pages/global.css

This PR aims to add the Select component.
Blocked PR until merge of #39.

feat(client): added Select component

---

client/package.json
client/pnpm-lock.yaml
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/dashboard/UserStore.ts
client/src/pages/dashboard/stores/UserStore.ts
client/src/pages/sw.ts

This PR aims to implement API caching in `sw.ts` and to migrate session API calls in components to a svelte store.

feat(client): implement API caching and Svelte store migration

---

client/src/components/ui/Button.svelte
client/src/components/ui/Modal.svelte
client/src/components/ui/contextdrawer/InboxContext.svelte
client/src/components/ui/contextmenu/ContextTemplate.svelte
client/src/components/ui/forms/GlobalPermissions.svelte
client/src/components/ui/navigationbar/SideDrawer.svelte
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/dashboard/stores/UserStore.ts
client/src/pages/dashboard/views/Sandbox.svelte

This PR adds the GlobalPermissions modification form. Take note that a user needs to have `UpdateUser` perms.

feat(client): add modify GlobalPermissions form

---

server/src/database.test.ts
server/src/database.ts
tests/api.test.ts

In response to the issues that @Arukuen faced with untested functions, this PR finally adds unit tests and integration tests for the `Batch.getEarliestBatch` function.

test(server/db): add unit tests for earliest batch

---

client/src/api/document.ts
client/src/components/ui/BarcodeSelect.svelte
client/src/components/ui/TextInput.svelte
client/src/components/ui/forms/document/CreateDocument.svelte
client/src/pages/dashboard/stores/BatchStore.ts
client/src/pages/dashboard/views/Barcodes.svelte
client/src/pages/dashboard/views/Sandbox.svelte

This PR adds the document creation form as a component. The sandbox implementation and styles are yet to be implemented. Feel free to add commits to accommodate for this.

feat(client): add document creation component

---

client/src/components/ui/navigationbar/TopBar.svelte
client/src/pages/dashboard/stores/NetState.ts
client/src/pages/vars.css

Warning: Network State does not change properly in Mozilla and Opera. See more https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine.
This PR aims to implement the Network State sensing, `TopBar` color changes on network state - and notifications by #73 are now implemented to inform user of network state.

feat(client): implement network state sense

---

client/src/api/staff.ts
model/src/api.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/staff.ts
server/src/routes/mod.ts
tests/api.test.ts

Per special request of @Arukuen, this PR implements a new API endpoint for getting the list of staff members given an office ID.

feat(server): implement endpoint for staff getter

---

client/src/components/ui/Toast.svelte
client/src/components/ui/forms/category/CreateCategory.svelte
client/src/components/ui/forms/category/RenameCategory.svelte
client/src/components/ui/forms/document/CreateDocument.svelte
client/src/components/ui/forms/document/InsertSnapshot.svelte
client/src/components/ui/forms/office/AddInvite.svelte
client/src/components/ui/forms/office/EditOffice.svelte
client/src/components/ui/forms/office/NewOffice.svelte
client/src/components/ui/forms/office/RevokeInvite.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/forms/staff/RemoveStaff.svelte
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/dashboard/stores/ToastStore.ts
client/src/pages/dashboard/views/Barcodes.svelte
client/src/pages/vars.css

This PR changes all invocations of `alert` with our custom toast message.

feat(client): implement basic error handling

---

client/src/components/ui/OfficeSelect.svelte
client/src/components/ui/TextInput.svelte
client/src/components/ui/navigationbar/SideDrawer.svelte
client/src/components/ui/navigationbar/TopBar.svelte
client/src/pages/dashboard/views/Dossier.svelte
client/src/pages/track/Track.svelte

- Papertrail shows 'time elapsed' since the previous change
- Papertrail shows OfficeName on target rather than OfficeID

fix(client): fix paper trail

---

server/src/database.test.ts
server/src/database.ts

This PR fixes the localMetrics SQL query and adds relevant database side tests.

feat(server): fixed localMetrics SQL query

---

client/src/components/ui/MetricsSelect.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/navigationbar/SideDrawer.svelte
client/src/pages/dashboard/views/Metrics.svelte

This PR aims to:
- Permission-based items in side drawer
- Permission-based options in metrics select
Closes #119

feat(client): implement permission-based visibility

---

client/src/components/ui/Toast.svelte

This PR aims to add a close button for the toast message. 
Closes #115

feat(client): add close button to toast
