BastiDood/doc-track

client/package.json

Last Wednesday, I noticed how much a hassle it was for everyone to keep running `pnpm build` before changes register in the front end. This PR alleviates that workflow by introducing `pnpm watch`, which watches over the dependency graph of Parcel and recompiles files _as needed_. This should significantly improve the feedback loop because `pnpm build` builds from scratch whereas `pnpm watch` only recompiles assets that have changed. We still have to force-reload the browser window, though.

dev(client): add file watcher script

---

server/src/cache.ts
server/src/model/oauth/openid.ts
server/src/routes/auth/callback.ts
server/src/routes/auth/login.ts
server/src/routes/auth/util.ts

This PR extracts the server's caching logic for [OpenID-related details](https://developers.google.com/identity/openid-connect/openid-connect). They are now located in the `server/src/cache.ts` folder from which all routes can retrieve the latest cached [discovery document](https://developers.google.com/identity/openid-connect/openid-connect#discovery).
One major implication of this change is that we now hit the cache for each request that requires the discovery document. Before, we only initialize the server and retrieve the discovery document from the cache **once** (during initialization). For the rest of the Deno program's lifetime, the server maintains an read-only, in-memory cache of the discovery document. It is never refreshed until the server shuts down and starts up again.
Now, …

refactor(server/cache): extract caching logic to own file

---

client/src/pages/register.ts

It turns out that the default behavior of the service worker registration is to set the scope (i.e., the allowed paths of interception) relative to the current directory of the resource registering the object. [See the MDN page on the `register` function.](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#examples)
That means we have a funny edge case where if the user happens to visit `/dashboard` first, the service worker's scope will be registered at `/dashboard` **only**. That means we will not be able to intercept requests from `/` (and its descendants such as `/api`). This is a bug!
This PR addresses the issue by explicitly setting the scope of the service worker to `/` at all times.

fix(client/sw): ensure service worker scope is `/`

---

client/src/api/metrics.ts
model/src/api.ts

As a continuation of #25, this PR implements the client-side wrapper for the `/api/metrics/user` API endpoint.

feat(client/api): implement wrapper for user metrics getter

---

client/package.json
client/pnpm-lock.yaml
client/src/api/batch.ts
client/src/api/category.ts
client/src/api/document.ts
client/src/api/invite.ts
client/src/api/metrics.ts
client/src/api/office.ts
client/src/api/session.ts
client/src/api/snapshot.ts
client/src/api/staff.ts
client/src/api/user.ts
client/src/api/vapid.ts

This shouldn't introduce any breaking changes. The dependency change is necessary for future work in the integration testing because `http-status` is more difficult to work with across server and client boundaries.

deps(client): migrate from `http-status` to `http-status-codes`

---

client/src/components/types.ts
client/src/components/ui/itemrow/AcceptRow.svelte
client/src/components/ui/itemrow/InboxRow.svelte
client/src/components/ui/itemrow/InviteRow.svelte
client/src/components/ui/itemrow/PersonRow.svelte

This PR aims to use the files in `modals` as the type annotations in our client components from this point on.

feat(client): enforced model type annotations in client

---

client/src/api/office.ts
model/src/permission.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/office.ts
server/src/routes/mod.ts

This PR adds the API endpoint `GET /api/offices` (note the plural!), which fetches a list of all the offices in the system. It rejects requests without a valid session ID with sufficient permissions.
This is necessary so that we can provide a dropdown menu of offices to the dashboard whenever a staff member wishes to send a document to another office.

feat(api): get all offices in the system

---

client/src/api/office.ts
client/src/components/ui/TextInput.svelte
client/src/components/ui/forms/EditOffice.svelte
client/src/components/ui/forms/GlobalPermissions.svelte
client/src/components/ui/forms/NewOffice.svelte
client/src/pages/Home.svelte
client/src/pages/dashboard/stores/OfficeStore.ts
client/src/pages/dashboard/views/Sandbox.svelte

This PR aims to add add Office Management Components (dialogs). 
NOTE: The selection method in `EditOffice.svelte` will be changed to a dropdown when the appropriate PR is pushed.

feat(client): implement Office Management Components

---

client/src/api/session.ts
model/src/api.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/session.ts
tests/api.test.ts

This PR expands the `GET /api/session` endpoint so that it also returns a dictionary of local permissions (with respect to their respective office IDs). There should be no breaking changes on the client side because we are only adding new fields.

feat(api): expand session getter so that it includes local permissions

---

server/src/database.test.ts
server/src/database.ts
server/src/routes/api/office.ts
tests/api.test.ts

Currently, it is impossible to set a user's local permissions because there was no superuser that set their permissions to begin with (i.e., via the Invite API). This PR addresses this by treating the creator of offices as the respective superusers—similar to how Discord treats server owners as superusers.

feat(server): treat office creators as superuser by default

---

client/src/components/ui/Button.svelte
client/src/components/ui/forms/office/NewOffice.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/pages/dashboard/views/Sandbox.svelte

This PR aims to add the LocalPermissions form component. Form is user agnostic and does not rely on the `$userSession` store.
Blocked by requisite PR #49.

feat(client): add LocalPermissions form component

---

client/src/api/office.ts
client/src/components/ui/OfficeSelect.svelte
client/src/components/ui/forms/office/EditOffice.svelte
client/src/components/ui/forms/office/NewOffice.svelte
client/src/pages/dashboard/stores/OfficeStore.ts
client/src/pages/dashboard/views/Sandbox.svelte
model/src/api.ts
model/src/office.ts
server/deno.json
server/src/database.test.ts
server/src/database.ts
tests/api.test.ts

Per @justinruaya123's suggestion, this PR changes the return type of the `GET /api/offices` endpoint to return a dictionary of office IDs and names instead of a plain array of offices. This is more ergonomic because the dictionary allows $O(1)$ lookup.

refactor(server): prefer dictionaries over arrays of offices

---

client/src/api/metrics.ts
model/src/api.ts
model/src/metrics.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/metrics.ts
server/src/routes/mod.ts
tests/api.test.ts

Blocked by #56.
This PR finally completes the basic implementation of the Metrics API.
Endpoint | Description | Permission
--- | --- | ---
`GET /api/metrics/user` | User-level Metrics | `Global.ViewMetrics`
`GET /api/metrics/office` | Office-level Metrics | `Local.ViewMetrics`
`GET /api/metrics/system` | System-level Metrics | `Global.ViewMetrics`
For all endpoints, they return a `Record<Status, number>` as JSON. Additional information such as average turnaround times may be implemented in a future PR.

feat(server): full Metrics API implementation

---

client/.eslintrc.cjs
client/package.json
client/pnpm-lock.yaml
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/dashboard/stores/UserStore.ts
client/src/pages/dashboard/views/Sandbox.svelte

PR aims to add a `currentUser` store that derives from the `userSession` store. This allows us to give to certain components only a subset of the information in a `userSession` for an easier time. i.e. Top nav does not need anything aside from the name, so we give it `currentUser` store instead of an entire `userSession` store.

feat(client): create currentUser to derive from (full) userSession.

---

client/src/components/icons/Hamburger.svelte
client/src/components/icons/icon-styles.css
client/src/components/types.ts
client/src/components/ui/Button.svelte
client/src/components/ui/RowTemplate.svelte
client/src/components/ui/forms/category/ActivateCategory.svelte
client/src/components/ui/forms/category/CreateCategory.svelte
client/src/components/ui/forms/category/RemoveCategory.svelte
client/src/components/ui/forms/category/RenameCategory.svelte
client/src/components/ui/forms/document/InsertSnapshot.svelte
client/src/components/ui/forms/office/EditOffice.svelte
client/src/components/ui/forms/office/NewOffice.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/itemrow/AcceptRow.svelte
client/src/components/ui/itemrow/InboxRow.svelte
client/src/components/ui/itemrow/InviteRow.svelte
client/src/components/ui/itemrow/PersonRow.svelte
client/src/components/ui/itemrow/SendRow.svelte
client/src/components/ui/navigationbar/SideDrawer.svelte
client/src/components/ui/navigationbar/TopBar.svelte
client/src/pages/Home.svelte
client/src/pages/dashboard/views/Sandbox.svelte

- Navigation 
1. Changed TopBar nav to have white elements.
2. Moved `OfficeSelect` to the SideBar
- Other UI
4. Fixed Buttons to be white when surrounded by a dark background.
5. By default, SVG icons are black. Use `IconColor.White` to change svg buttons to white.
6. Fixed RowElements to look more reasonably presentable
7. Removed unneeded button filters.

fix(client): ui fixes

---

client/src/api/vapid.ts
client/src/components/ui/Button.svelte
client/src/components/ui/Modal.svelte
client/src/components/ui/contextmenu/ContextTemplate.svelte
client/src/components/ui/forms/category/ActivateCategory.svelte
client/src/components/ui/forms/category/RemoveCategory.svelte
client/src/components/ui/forms/document/InsertSnapshot.svelte
client/src/components/ui/forms/office/EditOffice.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/forms/permissions/util.ts
client/src/components/ui/navigationbar/SideDrawer.svelte
client/src/components/ui/navigationbar/TopBar.svelte
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/dashboard/stores/DashboardState.ts
client/src/pages/dashboard/views/Barcodes.svelte
client/src/pages/dashboard/views/Drafts.svelte
client/src/pages/dashboard/views/Inbox.svelte
client/src/pages/dashboard/views/Invites.svelte
client/src/pages/dashboard/views/Metrics.svelte
client/src/pages/dashboard/views/Outbox.svelte
client/src/pages/dashboard/views/Sandbox.svelte
client/src/pages/dashboard/views/Staff.svelte

This PR was originally an implementation of @justinruaya123's original adaptive title bar, but with reactive statements instead. However, I ended up resolving all non-`alert` and non-`console` lint warnings along the way. Here are some the techniques I used to resolve them:
Simply cast the `enum` as a `Number` during runtime.
```diff
- res.status === Status.OK
+ res.status === Number(Status.OK)
```
Use an `as`-cast (not a type annotation!) to disallow TypeScript from type-narrowing too aggressively.
```diff
- export let submit = false;
+ export let submit = false as boolean;
```
There were also some warnings on unnecessary optional chaining. Indeed, we did this so that we always check whether an async store contains a value. However, the more idiomatic implementation is to simply `await` …

feat(client): adapt document title according to current office + resolve most lint warnings

---

client/src/components/types.ts
client/src/components/ui/MetricsSelect.svelte
client/src/components/ui/StatusSelect.svelte
client/src/components/ui/forms/document/InsertSnapshot.svelte
client/src/pages/dashboard/views/Metrics.svelte

In #68, I mistakenly inlined the `Select` component into its raw `<select>` and `<option>` counterparts to "simplify" the markup. It turns out that this had the funny consequence where all selection menus now have the wrong CSS styles.
This PR resolves this issue by reinstating the previously generic `Select` components into the more specialized `MetricsSelect` and `StatusSelect` components.
There is too much duplication of the same CSS `<style>`. At this point, we should just move the `select` and `select:focus` queries into some `global.css`.

feat(client): reinstate generic select components as specializations

---

client/src/components/icons/icon-styles.css
client/src/components/types.ts
client/src/components/ui/RowTemplate.svelte
client/src/components/ui/forms/category/ActivateCategory.svelte
client/src/components/ui/forms/category/RemoveCategory.svelte
client/src/components/ui/itemrow/AcceptRow.svelte
client/src/components/ui/itemrow/InboxRow.svelte
client/src/components/ui/itemrow/InviteRow.svelte
client/src/components/ui/itemrow/PersonRowGlobal.svelte
client/src/components/ui/itemrow/PersonRowLocal.svelte
client/src/components/ui/itemrow/RegisterRow.svelte
client/src/components/ui/itemrow/SendRow.svelte
client/src/components/ui/itemrow/chip-style.css
client/src/components/ui/itemrow/util.ts
client/src/pages/dashboard/views/Inbox.svelte
client/src/pages/dashboard/views/Outbox.svelte
client/src/pages/vars.css

This PR aims to change the respective `RowElementComponents` to a grid layout and a chip based design to display relevant information.
1. Change inner `RowElement` layout to a grid.
2. Use chips to display relevant `RowElement` information.
3. Stage redirect to redirect the `RowElement` to the respective tracking page.
**Hotfix**
1. Revert Inbox/Outbox RowElement enumerators to read from the store rather than the result of the `await load` operation.
2.

feat(client): implement chips information display in `RowElementComponent`

---

client/src/notification.ts

This PR implements the `sendNotification` helper function. It essentially keeps looping until the user explicitly _grants_ or _denies_ permissions.

feat(client): implement notification request helper

---

client/src/components/types.ts
client/src/components/ui/contextdrawer/PersonContext.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/forms/staff/RemoveStaff.svelte
client/src/components/ui/itemrow/PersonRowLocal.svelte
client/src/pages/dashboard/stores/StaffStore.ts
client/src/pages/dashboard/views/Invites.svelte
client/src/pages/dashboard/views/Sandbox.svelte
client/src/pages/dashboard/views/Staff.svelte

This pull request aims to:
- Add store `staffList`
- Remove `EditLocalPermission` from `Sandbox`
- Change the argument of `EditLocalPermission` from seprate `Office` and `User` to a `PersonPayload`
- Handle `EditLocalPermission` and `RemoveStaff` in `Staff` subpage
Note: `pnpm lint` results to `HeapError` in local machine. Will do linting based on the checks here.

feat(client): implementation of staffs subpage

---

client/src/api/user.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/user.ts
server/src/routes/mod.ts
tests/api.test.ts

As required by @Arukuen's sprint goals, this PR implements the `GET /api/users` endpoint, which returns an array of all the `User` instances in the system.
```ts
// In the future, we may want to turn `User[]` into a `UsersRecord` instead.
type UsersRecord = Record<User['id'], Omit<User, 'id'>>;
```
```ts
// Note that reloading the current user should imply reloading the full user registry.
allUsers.reload?.();
currentUser.reload?.();
```

feat(server): implement users getter endpoint

---

client/src/components/types.ts
client/src/components/ui/contextdrawer/InviteContext.svelte
client/src/components/ui/contextdrawer/PersonContextGlobal.svelte
client/src/components/ui/contextdrawer/PersonContextLocal.svelte
client/src/components/ui/forms/office/RevokeInvite.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/itemrow/PersonRowGlobal.svelte
client/src/components/ui/itemrow/PersonRowLocal.svelte
client/src/components/ui/navigationbar/SideDrawer.svelte
client/src/pages/dashboard/stores/UserStore.ts
client/src/pages/dashboard/views/Admins.svelte
client/src/pages/dashboard/views/Invites.svelte
client/src/pages/dashboard/views/Sandbox.svelte
client/src/pages/dashboard/views/Staff.svelte
client/src/pages/dashboard/views/Users.svelte
client/src/pages/dashboard/views/index.ts

This pull request aims to:
- Rename `Admin` to `Users` subpage
- Add `userList `store
- Remove `EditGlobalPermission `from Sandbox
- Change the argument of `EditGlobalPermission` from separate User to a `PersonPayload`
- Display Users and handle `EditGlobalPermission `in User subpage
Note: `pnpm lint` results to `HeapError `in local machine. Will do linting based on the checks here.
Note:  Still follows the old convention (event-based) instead of @BastiDood suggestion of using state-transition based. Will refractor after PR #79 is merged.

feat(client): implementation of Users subpage

---

client/src/api/document.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/document.ts
server/src/routes/api/snapshot.ts
server/src/routes/mod.ts
tests/api.test.ts

As needed by @SporadicToast's sprint goals, this PR implements the API endpoint `GET /api/dossier?office={oid}`, which retrieves the "dossier" of a given office. The dossier is essentially a list of documents (a.k.a., `InboxEntry[]`) that the office has registered themselves (regardless of the current snapshot of the document).
Normally, these documents would disappear from the office inbox once received by the target office. Now, this endpoint enables the source office to nevertheless view all their sent documents so that they may view its paper trail.

feat(server): implement dossier getter

---

client/src/api/metrics.ts
model/src/api.ts
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/metrics.ts
server/src/routes/mod.ts
tests/api.test.ts

As needed by @Arukuen, this PR implements basic metrics (via the `GET /api/metrics/barcode` endpoint) for office barcodes.

feat(server): implement barcode metrics

---

client/src/components/types.ts
client/src/components/ui/contextdrawer/AcceptContext.svelte
client/src/components/ui/contextdrawer/InboxContext.svelte
client/src/components/ui/contextdrawer/InviteContext.svelte
client/src/components/ui/contextdrawer/PersonContextGlobal.svelte
client/src/components/ui/contextdrawer/PersonContextLocal.svelte
client/src/components/ui/forms/document/CreateDocument.svelte
client/src/components/ui/forms/document/InsertSnapshot.svelte
client/src/components/ui/forms/office/AddInvite.svelte
client/src/components/ui/forms/office/RevokeInvite.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/forms/staff/RemoveStaff.svelte
client/src/components/ui/itemrow/AcceptRow.svelte
client/src/components/ui/itemrow/InboxRow.svelte
client/src/components/ui/itemrow/InviteRow.svelte
client/src/components/ui/itemrow/PersonRowGlobal.svelte
client/src/components/ui/itemrow/PersonRowLocal.svelte
client/src/components/ui/itemrow/RegisterRow.svelte
client/src/pages/dashboard/views/Barcodes.svelte
client/src/pages/dashboard/views/Inbox.svelte
client/src/pages/dashboard/views/Invites.svelte
client/src/pages/dashboard/views/Outbox.svelte
client/src/pages/dashboard/views/Staff.svelte
client/src/pages/dashboard/views/Users.svelte

This PR extends the `state-machine` concept by @BastiDood in #79 and implements it in all pages that use this.
This also removes all the imports and dependencies that were used by the versions of dispatching dialogs.
PS: As an after-effect of these modifications - dialogs now close when the intended operations are done.

refactor(client): prefer state-machines to manage dialogs

---

client/src/api/batch.ts
client/src/api/category.ts
client/src/api/document.ts
client/src/api/error.ts
client/src/api/invite.ts
client/src/api/metrics.ts
client/src/api/office.ts
client/src/api/session.ts
client/src/api/staff.ts
client/src/api/user.ts
client/src/pages/dashboard/stores/BatchStore.ts
client/src/pages/dashboard/stores/CategoryStore.ts
client/src/pages/dashboard/stores/DocumentStore.ts
client/src/pages/dashboard/stores/InviteStore.ts
client/src/pages/dashboard/stores/MetricStore.ts
client/src/pages/dashboard/stores/StaffStore.ts
client/src/pages/dashboard/stores/UserStore.ts
client/src/pages/sw.ts

This PR utilizes the Toasts implemented in #88 to notify the user of any network errors and expands on the capability of the Store to present errors to the user.
A new type of error that is raised when the user goes offline but the PWA is unable to perform in offline mode due to not being able to cache enough information.
The system now toasts when a user attempt to access a page without selecting an active office.
Blocked by #94

feat(client): Stores/Offline Error Handling

---

client/src/components/types.ts
client/src/components/ui/Toast.svelte
client/src/components/ui/forms/batch/GenerateBatch.svelte
client/src/components/ui/forms/category/CreateCategory.svelte
client/src/components/ui/forms/category/RenameCategory.svelte
client/src/components/ui/forms/document/CreateDocument.svelte
client/src/components/ui/forms/document/InsertSnapshot.svelte
client/src/components/ui/forms/invite/AddInvite.svelte
client/src/components/ui/forms/invite/RevokeInvite.svelte
client/src/components/ui/forms/office/EditOffice.svelte
client/src/components/ui/forms/office/NewOffice.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/forms/staff/RemoveStaff.svelte
client/src/components/ui/itemrow/SendRow.svelte
client/src/pages/dashboard/Dashboard.svelte
client/src/pages/dashboard/stores/DeferredStore.ts
client/src/pages/dashboard/stores/ToastStore.ts
client/src/pages/dashboard/views/Barcodes.svelte
client/src/pages/dashboard/views/Categories.svelte
client/src/pages/dashboard/views/Inbox.svelte
client/src/pages/dashboard/views/Invites.svelte
client/src/pages/dashboard/views/Outbox.svelte
client/src/pages/vars.css

This PR aims to:
- Add Toast Types: Info, Success, Error, and Offline (default is Error)
- Prefer toast instead of confirmation modals
- Add toast reminder when office is not yet selected

feat(client): add toast type

---

client/src/api/document.ts
client/src/pages/Home.svelte
client/src/pages/dashboard/views/Inbox.svelte
client/src/pages/dashboard/views/Outbox.svelte
client/src/pages/track/Track.svelte
model/src/api.ts
model/src/snapshot.ts
server/deno.json
server/deno.lock
server/src/database.test.ts
server/src/database.ts
server/src/routes/api/document.ts
tests/deno.json
tests/deno.lock

As its name suggests, this PR implements the file download button for the paper trail. Currently, the name of the downloaded file conforms to the `{id}.{mime}` format, where `id` is the document's UUID and `mime` is the file extension associated with its MIME type. In future PRs, we may consider using `document.title`, but that requires us to sanitize the file name in case it contains nasty characters.

feat: implement file download mechanism

---

client/src/notification.ts
client/src/pages/sw.ts

This PR fixes an oversight I had when implementing the web push notifications: the icon! Now that #106 is merged *thanks to @justinruaya123!), we now have an icon for all push notifications.

feat(client): add icon to web push notifications

---

client/src/stores/NetState.ts

Currently, the offline toast message is too long to be read in three seconds. This PR extends the timeout to eight seconds.
Ideally, we should keep these timeouts long, anyway, but let the user dismiss it using a close button. The infrastructure for that is already implement using the `topToastMessage.dismiss` function. We just need to hook into the UI in future PRs.

fix(client): lengthen the timeout for offline notifications

---

client/src/components/ui/Toast.svelte

This PR introduces sliding transitions to the toast messages. I also rounded out the corners of the toast message some more while removing the bottom rounded corners. This makes the sliding transition more "seamless" and "flush" with the bottom of the screen.

feat(client): toast message sliding transitions

---

client/src/pages/track/Track.svelte

Closes #121.
In addition to displaying the profile picture, I also referred to the staff member by their name. Clicking on their link sends the user to a `mailto:` link, which should open their default email client and draft an email to the staff member.

feat(client): display profile picture and email in paper trail

---

client/src/components/ui/Button.svelte
client/src/components/ui/Modal.svelte
client/src/components/ui/forms/office/NewOffice.svelte
client/src/components/ui/forms/staff/AddStaff.svelte
client/src/components/ui/forms/staff/RemoveStaff.svelte
client/src/pages/dashboard/views/Office.svelte
client/src/pages/dashboard/views/Staff.svelte
server/deno.json
server/src/routes/mod.ts

Blocked on #130. Continues the work from #129 and finally closes #117.
This PR implements the staff adder button, which allows an office administrator to manually add existing users into an office (assuming that the office administrator already knows the user's Google ID). In the process, I was able to refactor the `Staff.svelte` subview to use the state machine pattern.

feat(client): implement staff adder button

---

client/src/pages/dashboard/views/Staff.svelte

This PR aims to add a selection to show staff that have no permissions so that a person with authority can escalate their permissions as needed. Continues #132  , finally resolves #117.

feat(client): display staff without permissions

---

COPYING.md
client/src/components/ui/MetricsSelect.svelte
client/src/components/ui/forms/permissions/GlobalPermissions.svelte
client/src/components/ui/forms/permissions/LocalPermissions.svelte
client/src/components/ui/forms/permissions/util.ts
client/src/components/ui/navigationbar/SideDrawer.svelte

This PR aims to:
- Implement deep permission-based visibility, that is, if no permission is set in the corresponding to the subpage, then the subpage item is not visible to the side drawer.

feat(client): implement deep permission-based visibility in side drawer
